spring.application.name=scm2.0

# MySQL Databse Configurations
spring.config.activate.on-profile=local
spring.datasource.url=jdbc:mysql://localhost:3306/scm2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

#  JPA Configurations
spring.jpa.show-sql=true


