spring.application.name=scm2.0

# MySQL Databse Configurations
# spring.config.activate.on-profile=local
spring.datasource.username=root
spring.datasource.password=root

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=MyHikariCP

# Hikari CP Metrics 

management.endpoints.web.exposure.include=health,metrics

# Logging Properties

logging.file.name=/Users/siddharth/Desktop/Smart Contact Manager/logs/app.log
logging.level.root=INFO




